version: 1.0

images:
  nginx:
    local_port: 80
  image_name:
    local_port: 81
app_conf:
  port_start: 40000
  port_end: 60000
  app_port: 5015
  host: "http://127.0.0.1"
  debug: False

credentials:
  admin: admin
  user: user
